### ISSUE TITLE
Release 0.5 missing functionality

### ISSUE THREAD

**Issue by TimUntersberger** [tarkah/grout#25]
I just downloaded release 0.5 and I think the quick resize keybind is still doing the normal resize.

config.yml
```yaml
margins: 0
window_padding: 0
hotkey_quick_resize: CTRL+ALT+Q
auto_start: true
```

I just tried every release between 0.5 and 0.3 and the problem only occured after release 0.5.

I also looked through the commits between 0.4.1 and 0.5 and I believe that the commit 23aad8dcd0ccca3b973ccbec8968b749eaf36f14 somehow broke this.
